### Introducción a Numpy

In [1]:
# Importamos la librería
!pip install numpy #por si no lo tenemos instalado

In [2]:
import numpy as np

El core de numpy es el objeto ndarray, el cual puede tomar multples dimensiones.

In [7]:
# Crear un array de 2D

array_2d = np.array([[1,2,3],[3,5,6]])
print(array_2d)

[[1 2 3]
 [3 5 6]]


In [8]:
print(type(array_2d))

<class 'numpy.ndarray'>


In [9]:
#TRANSPONER LA MATRIZ
array_2d.T

array([[1, 3],
       [2, 5],
       [3, 6]])

ATRIBUTOS PRINCIPALES QUE TIENE NUESTRO OBJETO NUMPY ARRAY

- ndim: dimensión del array
- shape: tupla con #numero filas, numero columnas
- dtype: tipo de dato que tenemos en el array (todos los elemnetos deben ser del mismo tipo)

In [17]:
array = np.array([[1,2,3,4], [5,6,7,8], [4,6,9,0]])

print(f"Array: \n{array}")
print('\n')
print(f'Numero de dimensiones (ndim): {array.ndim}')
print(f'Numero de dimensiones (ndim): {array.shape}')
print(f'Data type (dtype): {array.dtype}')

Array: 
[[1 2 3 4]
 [5 6 7 8]
 [4 6 9 0]]


Numero de dimensiones (ndim): 2
Numero de dimensiones (ndim): (3, 4)
Data type (dtype): int64


In [19]:
array_mixto = np.array([
    [1,2,"3"],
    [4,5,6]
]) 

print(f'Data type (dtype): {array_mixto.dtype}')

Data type (dtype): <U21


## Array Indexing

Acceder a los elementos de un numpy array es similar a la sintacis de las listas

In [23]:
# Caso lista
lista = ['a', 'b', 'c']
print(f'Elemento en la posicion 2: {lista[2]}')

Elemento en la posicion 2: c


Para acceder a un array tenemos las sigs. opciones:

- Elemento especifico: array[fila, columna]
- Slicing: usamos "colons (:)"para selecciionar columnas/filas enteras o rangos de cada uno.
- indice negarivo: contamos desde atras en los elemntoa

In [30]:
vector = np.array([12,11,20,35,40])

# ELEMENTO ESPECIFICO
print(f'Elemento 1 de mi vector: {vector[1]}')

# SLICING
print(f'Los primeros n elementos de mi vector: {vector[0:3]}')
print(f'Los primeros n elementos de mi vector: {vector[2:5]}')

# INDICE NEGATIVO
print(f'Ultimo Elemento de mi vector: {vector[-1]}')

Elemento 1 de mi vector: 11
Los primeros n elementos de mi vector: [12 11 20]
Los primeros n elementos de mi vector: [20 35 40]
Ultimo Elemento de mi vector: 40


Operaciones con matrices

In [35]:
# GENERA UN ARRAY DE 25 ENTRADAS Y DESPUES RE ACOMODAR LOS DATOS

matrix = np.arange(25).reshape(5,5) # creamos una matrix 5x5
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
# ACCESO A UN ELEMENTO EN ESPECÍFICO
print(f'Elemento en la posicion (1,2): {matrix[1,2]}')

# SELECCIONAR UNA FILA COMPLETA DE LA MATRIZ 
print(f' \n Primera fila de la matriz: {matrix[0,:]}')

# SELECIONAR LA ULTIMA COLUMNA
print(f' \n Ultima columna de la matriz: {matrix[:,-1]}')

# SLICING DE UNA MATRIZ
print(f'\n Submatriz  (filas 0-2) y columnas 0-1 {matrix[0:3,0:2]}')

Elemento en la posicion (1,2): 7
 
 Primera fila de la matriz: [0 1 2 3 4]
 
 Ultima columna de la matriz: [ 4  9 14 19 24]

 Submatriz  (filas 0-2) y columnas 0-1 [[ 0  1]
 [ 5  6]
 [10 11]]


In [45]:
#Reversing a row from a vector
print(f'Vector reversed: {vector[::-1]}')

Vector reversed: [40 35 20 11 12]


In [47]:
print(f'Row of a matrix reversed: {matrix[0,::-1]}')

Row of a matrix reversed: [4 3 2 1 0]


In [51]:
#asignacion
matrix[[0,-1]] = 0
matrix

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  0,  0,  0,  0]])

In [56]:
#GENERAR NOS. ALEATORIOS ENTEROS
random_numbers = np.random.randint(low = -100, high = -1, size = (2,5))
random_numbers

array([[-91, -72,  -5, -93, -78],
       [-58, -56, -79,  -2, -14]])

## OPERACIONES CON ARRAYS

- Una de las habilidades de NUMPY es que puedes hacer operaciones vectorizadas

In [64]:
array_1 = np.array([[2, 4, 6],
                    [3, 5, 1]])

print(f'Original array 1: \n: {array_1}')

Original array 1: 
: [[2 4 6]
 [3 5 1]]


In [66]:
#sumar un escalar
print(f'array_1 +1: \n {array_1 + 1}')

#elevar al cuadrado
print(f'array_1 ˆ2 \n {array_1 ** 2}')

# operaciones con condicionales
print(f'\n array_1 <= 3 \n {array_1 <= 3}')

array_1 +1: 
 [[3 5 7]
 [4 6 2]]
array_1 ˆ2 
 [[ 4 16 36]
 [ 9 25  1]]

 array_1 <= 3 
 [[ True False False]
 [ True False  True]]


##  Secuencias con numpy

- np.arange(start,stop,step)
- np.linspace(start,stop,num): regresa una muestra con elementos evenly spaced calculados osbre le intervalo

In [74]:
# crear secuencia con steps enteros:

print("np.arange(2,11,2): ", np.arange(2,11,2))

# creamos secuencia con steps flotantes
print("np.arange(2,3.5,0.1):", np.arange(2,3.5,0.1))

# Secuencia con numeros equidistantes:
print('np.linspace(1,10,21):', np.linspace(1,10,21))

np.arange(2,11,2):  [ 2  4  6  8 10]
np.arange(2,3.5,0.1): [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4]
np.linspace(1,10,21): [ 1.    1.45  1.9   2.35  2.8   3.25  3.7   4.15  4.6   5.05  5.5   5.95
  6.4   6.85  7.3   7.75  8.2   8.65  9.1   9.55 10.  ]


## Cambiar dimensiones de un array

- .reshape(new_shape): crea un nuevo array con la nueva dimension sin cambiar los datos
- .flatten(): regresa una copia del array colpasado en una 1 dimension

In [76]:
array = np.arange(25) #1D ARRAY WITH ELEMENTOS DEL 0-24
print('orignal array:', array)
print('original ndim:', array.ndim)
print('original shape', array.shape)

orignal array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
original ndim: 1
original shape (25,)


In [77]:
# reshape de nuestro array a una matrix de 5x5
array_reshaped = array.reshape(5,5)

print('Reshaped 5x5:', array_reshaped)
print('Reshaped ndim:', array_reshaped.ndim)
print('Reshaped shape', array_reshaped.shape)

Reshaped 5x5: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Reshaped ndim: 2
Reshaped shape (5, 5)


In [78]:
# regresar la matriz al vector se realiza asi:
array_flattened = array_reshaped.flatten()
print('\n flattened array',array_flattened)


 flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [84]:
# Creamos un array de zeros
print('Array de zeros (1D): \n', np.zeros(5))

# Creamos un array de zeros
print('Array de zeros: (2D) \n', np.ones((2,3)))

# creamos la matriz identidad 
print('\n Matriz identidad (5x5):', np.identity(5))

#creamos un array 2d con 1s en la diagonal y ceros en otras partes
print('\n Casi Matriz identidad (5x4):', np.eye(5,4))

Array de zeros (1D): 
 [0. 0. 0. 0. 0.]
Array de zeros: (2D) 
 [[1. 1. 1.]
 [1. 1. 1.]]

 Matriz identidad (5x5): [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 Casi Matriz identidad (5x4): [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


## ELEMENTOS ESTADISTICOS

In [90]:
# Generamos un vector con nos. aleatorios

random = np.random.randint(-100,100,10)
print('vector numeros aleatorios',random)
print('\n valor min:', random.min())
print('\n valor maz:', random.max())
print('\n indice del valor max:', random.argmax())
print('\n suma de todos los elementos:', random.sum())
print('\n media  delos elementos:', random.sum())
print('\n varianza de los elementos:', random.var())
print('\n suma acumulada de los elementos:', random.cumsum())


vector numeros aleatorios [  84 -100  -40   44  -84  -38  -12   -5  -91  -37]

 valor min: -100

 valor maz: 84

 indice del valor max: 0

 suma de todos los elementos: -279

 media  delos elementos: -279

 varianza de los elementos: 3112.69

 suma acumulada de los elementos: [  84  -16  -56  -12  -96 -134 -146 -151 -242 -279]


In [104]:
#generemos una matriz con numeros aleatorios
random_3d_array = np.random.randint(-100,100, size = (2,5,10))
print('3D ARRAY: \n', random_matrix)

#obtener la suma de todos los elementos
print('Suma de todos los elementos: ', random_3d_array.sum())

print('\n suma del primer slice () (random_3d_array[0].sum())', random_3d_array[0].sum())

#pasamos a solo 1 slice del array
slice_array = random_3d_array[0]
print(' \n sliced array: \n',slice_array)

#suma sobre columnas
print('Suma sobre axis=0', slice_array.sum(axis=0))



#suma sobre filas
print('Suma sobre axis=1', slice_array.sum(axis=1))

3D ARRAY: 
 [[[ 45  -2  48  -1 -38  96 -39 -24 -72 -56]
  [-39 -83 -78  67  48 -88 -38 -85  27  59]
  [ -3  65 -27 -40 -89 -36  44  -9 -83  33]
  [ 53 -40 -49  -4 -86  39 -63 -28 -13 -49]
  [ 86  33  43 -88  59  -7 -62  32 -39 -65]]

 [[ 37  76  59  10 -11 -46 -83  96  31 -95]
  [ 90  67 -54 -20 -69  63 -59 -95  44   2]
  [ 31  46  13  88  61 -78 -80  59  86  12]
  [ 56 -36  69  -7  80 -88 -83  96  30  -8]
  [-30 -46  13  32  59 -63 -47  73 -23  55]]]
Suma de todos los elementos:  -156

 suma del primer slice () (random_3d_array[0].sum()) -263
 
 sliced array: 
 [[  1 -24  12   3 -79  46  24 -94  92 -62]
 [ 57  19   4 -11  87 -65 -62  38  79  16]
 [-27  13  11 -26  20 -89  31  91 -34  55]
 [-12  15  23 -55 -44  21  -5 -11 -59  30]
 [-94 -70 -74  40  10 -59 -64 -44  -2  65]]
Suma sobre axis=0 [ -75  -47  -24  -49   -6 -146  -76  -20   76  104]
Suma sobre axis=1 [ -81  162   45  -97 -292]


Para calcular diferencias tenemos la funcion np.diff() la cual calcula la n diferencia sobre un eje

In [107]:
array = np.array([1,3,4,7,9])
print('original array', array)

# primera diferencia (n=1 por defecto)
print('first difference:', np.diff(array, n=1))

# SEGUNDA diferencia (n=2)
print('first difference:', np.diff(array, n=2))

# cambios porcentuales (ai - ai-1/ ai-1)
print('Pct cambios:', np.diff(array)/array[:-1])


original array [1 3 4 7 9]
first difference: [2 1 3 2]
first difference: [-1  2 -1]
Pct cambios: [2.         0.33333333 0.75       0.28571429]


## Para encontrar los elementos unicos de un vector

In [111]:
array = np.array([1,3,4,7,9,1,25])

#elementos unicos
print('Elementos unicos:',np.unique(array))

#elementos unicos y cuantos hay
unique_elements, counts = np.unique(array, return_counts =True)
print('Elementos unico y cuanors hays:', unique_elements, counts)

Elementos unicos: [ 1  3  4  7  9 25]
Elementos unico y cuanors hays: [ 1  3  4  7  9 25] [2 1 1 1 1 1]


## Multiplicación de matrices

Es importante diferenciar entre la mult *elemnt wise* (* o. np.multiply) contra la mult matricial  *matricial* (np.matmult o np.dot)

- A * B or np.multiply(A,B): genera mult elemento a elemento
- np.dot(A,B): def de producto . Para arrays de 2D aplica mult matricial, para arrays de 1D aplica innerproduct


In [119]:
A = np.arange(16).reshape(4,4)
print('Matriz A: \n', A)

#Element with mult
print('\n Mult A*A: \n', A*A)

#matrix mult
print('\n MATRIX MULT: \n', np.dot(A,A))

B_Vector = np.arange(4) #1d vector
print('Vector B: \n', B_Vector)

# Dot product
print('DOCT PRODUCT A, B: \n', np.dot(A,B_Vector))


Matriz A: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Mult A*A: 
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]

 MATRIX MULT: 
 [[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]
 [344 398 452 506]]
Vector B: 
 [0 1 2 3]
DOCT PRODUCT A, B: 
 [14 38 62 86]


In [120]:
# TRANSPONER MATRICES
A.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [121]:
B_Vector.T

array([0, 1, 2, 3])

## ALGEBRA LINEAL

In [136]:
A = np.random.randint(5, size = (2,2))
print('Matriz A: \n', A)

# Inversa de la matriz
inv_A = np.linalg.inv(A)
print('Inversa de A: \n', inv_A)

# verificamos que la inversa este bien calculada np.dot(A,inv_A) =identity matrix
print('\n A * inv_A \n: ', np.dot(A,inv_A))

# transpuesta
print('\n A transpuesta\n: ', np.transpose(A))

# determiannte
print('\n A DETERMINANTE \n: ', np.linalg.det(A))

# EIGEN VALORES
print('\n A eigenvalores \n: ', np.linalg.eigvals(A))

# RESOLVER ECS (Ax =b)
b = np.array([1,2])
print('\n Resolviendo Ax= b')
# x = A_inv *b
x = inv_A.dot(b)
print('sol',x)

Matriz A: 
 [[3 1]
 [4 3]]
Inversa de A: 
 [[ 0.6 -0.2]
 [-0.8  0.6]]

 A * inv_A 
:  [[ 1.00000000e+00 -1.11022302e-16]
 [ 2.22044605e-16  1.00000000e+00]]

 A transpuesta
:  [[3 4]
 [1 3]]

 A DETERMINANTE 
:  4.999999999999999

 A eigenvalores 
:  [5. 1.]

 Resolviendo Ax= b
sol [0.2 0.4]
